"""rename address

Revision ID: 4fae17c01eed
Revises: c938994146ab
Create Date: 2025-06-15 23:29:25.707673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fae17c01eed'
down_revision = 'c938994146ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name = 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name = 'address')
    # ### end Alembic commands ###
